=== tadamovsky/xsdexplorer/samples/abstract/absType.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:ns1="http://test.com/source/" targetNamespace="http://test.com/source/">
    <xsd:complexType name="PublicationType" abstract="true">
        <xsd:sequence>
            <xsd:element name="Title" type="xsd:string"/>
            <xsd:element name="Author" type="xsd:string" 
                         minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="Date" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
	
	<xsd:element name="Catalogue">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Publication" type="ns1:PublicationType" 
                             maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
	
  <xsd:complexType name="BookType">
        <xsd:complexContent>
            <xsd:extension base="ns1:PublicationType">
                <xsd:sequence>
                    <xsd:element name="ISBN" type="xsd:string"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="MagazineType">
        <xsd:complexContent>
            <xsd:extension base="ns1:PublicationType"/>
        </xsd:complexContent>
    </xsd:complexType>	
</xsd:schema>

=== tadamovsky/xsdexplorer/samples/abstract/asbTypeXmlSpy.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:Catalogue xmlns:ns1="http://test.com/source/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://test.com/source/ absType.xsd">
	<ns1:Publication xsi:type="ns1:BookType">
		<ns1:Title>String</ns1:Title>
		<ns1:Author>String</ns1:Author>
		<ns1:Author>String</ns1:Author>
		<ns1:Date>String</ns1:Date>
		<ns1:ISBN>String</ns1:ISBN>
	</ns1:Publication>
	<ns1:Publication xsi:type="ns1:BookType">
		<ns1:Title>String</ns1:Title>
		<ns1:Author>String</ns1:Author>
		<ns1:Author>String</ns1:Author>
		<ns1:Date>String</ns1:Date>
		<ns1:ISBN>String</ns1:ISBN>
	</ns1:Publication>
</ns1:Catalogue>
