=== tadamovsky/xsdexplorer/samples/simple/allSimpleTypes.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:notation name="jpeg" public="image/jpeg" system="file:///usr/bin/xv"/>
	<xs:notation name="png" public="image/gif" system="file:///usr/bin/xv"/>
	<xs:simpleType name="notationType">
		<xs:restriction base="xs:NOTATION">
			<xs:enumeration value="jpeg"/>
			<xs:enumeration value="png"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<!-- Simple types with various data types -->
				<!-- String-based types -->
				<xs:element name="myString" type="xs:string"/>
				<xs:element name="myNormalizedString" type="xs:normalizedString"/>
				<xs:element name="myToken" type="xs:token"/>
				<xs:element name="myLanguage" type="xs:language"/>
				<xs:element name="myNMTOKEN" type="xs:NMTOKEN"/>
				<xs:element name="myNMTOKENS" type="xs:NMTOKENS"/>
				<xs:element name="myName" type="xs:Name"/>
				<xs:element name="myNCName" type="xs:NCName"/>
				<xs:element name="myID" type="xs:ID"/>
				<xs:element name="myIDREF" type="xs:IDREF"/>
				<xs:element name="myIDREFS" type="xs:IDREFS"/>
				<!-- DTD reference
				<xs:element name="myENTITY" type="xs:ENTITY"/>
				<xs:element name="myENTITIES" type="xs:ENTITIES"/>
				-->
				<!-- Numeric types -->
				<xs:element name="myInteger" type="xs:integer"/>
				<xs:element name="myNonPositiveInteger" type="xs:nonPositiveInteger"/>
				<xs:element name="myNegativeInteger" type="xs:negativeInteger"/>
				<xs:element name="myLong" type="xs:long"/>
				<xs:element name="myInt" type="xs:int"/>
				<xs:element name="myShort" type="xs:short"/>
				<xs:element name="myByte" type="xs:byte"/>
				<xs:element name="myNonNegativeInteger" type="xs:nonNegativeInteger"/>
				<xs:element name="myUnsignedLong" type="xs:unsignedLong"/>
				<xs:element name="myUnsignedInt" type="xs:unsignedInt"/>
				<xs:element name="myUnsignedShort" type="xs:unsignedShort"/>
				<xs:element name="myUnsignedByte" type="xs:unsignedByte"/>
				<xs:element name="myPositiveInteger" type="xs:positiveInteger"/>
				<xs:element name="myDecimal" type="xs:decimal"/>
				<xs:element name="myFloat" type="xs:float"/>
				<xs:element name="myDouble" type="xs:double"/>
				<!-- Date and time types -->
				<xs:element name="myDuration" type="xs:duration"/>
				<xs:element name="myDateTime" type="xs:dateTime"/>
				<xs:element name="myTime" type="xs:time"/>
				<xs:element name="myDate" type="xs:date"/>
				<xs:element name="myGYearMonth" type="xs:gYearMonth"/>
				<xs:element name="myGYear" type="xs:gYear"/>
				<xs:element name="myGMonthDay" type="xs:gMonthDay"/>
				<xs:element name="myGDay" type="xs:gDay"/>
				<xs:element name="myGMonth" type="xs:gMonth"/>
				<!-- Miscellaneous types -->
				<xs:element name="myBoolean" type="xs:boolean"/>
				<xs:element name="myBase64Binary" type="xs:base64Binary"/>
				<xs:element name="myHexBinary" type="xs:hexBinary"/>
				<xs:element name="myAnyURI" type="xs:anyURI"/>
				<xs:element name="myQName" type="xs:QName"/>
				<xs:element name="myNOTATION" type="notationType"/>
				
				<!-- Complex mixed -->
				<xs:element name="noContent"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== tadamovsky/xsdexplorer/samples/simple/allSimpleTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="allSimpleTypes.xsd">
	<myString>String</myString>
	<myNormalizedString>normalizedString</myNormalizedString>
	<myToken>token</myToken>
	<myLanguage>en-us</myLanguage>
	<myNMTOKEN>NMTOKEN</myNMTOKEN>
	<myNMTOKENS>NMTOKEN</myNMTOKENS>
	<myName>Name</myName>
	<myNCName>NCName</myNCName>
	<myID>ID1</myID>
	<myIDREF>ID1</myIDREF>
	<myIDREFS>ID1</myIDREFS>
	<myInteger>0</myInteger>
	<myNonPositiveInteger>0</myNonPositiveInteger>
	<myNegativeInteger>-2</myNegativeInteger>
	<myLong>0</myLong>
	<myInt>0</myInt>
	<myShort>4096</myShort>
	<myByte>127</myByte>
	<myNonNegativeInteger>0</myNonNegativeInteger>
	<myUnsignedLong>4294967295</myUnsignedLong>
	<myUnsignedInt>0</myUnsignedInt>
	<myUnsignedShort>65535</myUnsignedShort>
	<myUnsignedByte>255</myUnsignedByte>
	<myPositiveInteger>2</myPositiveInteger>
	<myDecimal>0</myDecimal>
	<myFloat>3.141590118408203125</myFloat>
	<myDouble>3.1415926535897900073734945</myDouble>
	<myDuration>P1Y2M2DT10H30M</myDuration>
	<myDateTime>2001-12-17T09:30:47Z</myDateTime>
	<myTime>09:30:47+05:00</myTime>
	<myDate>1957-08-13</myDate>
	<myGYearMonth>2001-12</myGYearMonth>
	<myGYear>2001</myGYear>
	<myGMonthDay>--12-17</myGMonthDay>
	<myGDay>---17</myGDay>
	<myGMonth>--12</myGMonth>
	<myBoolean>true</myBoolean>
	<myBase64Binary>UjBsR09EbGhjZ0dTQUxNQUFBUUNBRU1tQ1p0dU1GUXhEUzhi</myBase64Binary>
	<myHexBinary>41394644363445313243</myHexBinary>
	<myAnyURI>http://www.altova.com/</myAnyURI>
	<myQName>xml:space</myQName>
	<myNOTATION>*** ERROR ***</myNOTATION>
</root>

=== tadamovsky/xsdexplorer/samples/simple/mySample.xml
<?xml version='1.0' encoding='UTF-8'?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="allSimpleTypes.xsd">
  <myString>String</myString>
  <myNormalizedString>String</myNormalizedString>
  <myToken>String</myToken>
  <myLanguage>r</myLanguage>
  <myNMTOKEN>c</myNMTOKEN>
  <myNMTOKENS>cc</myNMTOKENS>
  <myName>i</myName>
  <myNCName>i</myNCName>
  <myID>String</myID>
  <myIDREF>String</myIDREF>
  <myIDREFS>String</myIDREFS>
  <myInteger>0</myInteger>
  <myNonPositiveInteger>0</myNonPositiveInteger>
  <myNegativeInteger>-1</myNegativeInteger>
  <myLong>0</myLong>
  <myInt>0</myInt>
  <myShort>0</myShort>
  <myByte>0</myByte>
  <myNonNegativeInteger>0</myNonNegativeInteger>
  <myUnsignedLong>0</myUnsignedLong>
  <myUnsignedInt>0</myUnsignedInt>
  <myUnsignedShort>0</myUnsignedShort>
  <myUnsignedByte>0</myUnsignedByte>
  <myPositiveInteger>1</myPositiveInteger>
  <myDecimal>0.0</myDecimal>
  <myFloat>0.0</myFloat>
  <myDouble>0.0</myDouble>
  <myDuration>PT1004199059S</myDuration>
  <myDateTime>2001-10-26T21:32:52+02:00</myDateTime>
  <myTime>21:32:52</myTime>
  <myDate>2001-10-26</myDate>
  <myGYearMonth>2001-10</myGYearMonth>
  <myGYear>2001</myGYear>
  <myGMonthDay>--05-01</myGMonthDay>
  <myGDay>---17</myGDay>
  <myGMonth>--05</myGMonth>
  <myBoolean>false</myBoolean>
  <myBase64Binary>++++</myBase64Binary>
  <myHexBinary>3f3c</myHexBinary>
  <myAnyURI>String</myAnyURI>
  <myQName>String</myQName>
  <myNOTATION>jpeg</myNOTATION>
  <noContent>text</noContent>
</root>
